export const ADD_TO_CART_REQUEST = 'ADD_TO_CART_REQUEST'
export const ADD_TO_CART_SUCCESS = 'ADD_TO_CART_SUCCESS'
export const ADD_TO_CART_FAIL = 'ADD_TO_CART_FAIL'
export const CLEAR_ERROR = 'CLEAR_ERROR'

export const REMOVE_FROM_CART = 'REMOVE_FROM_CART'

export const SAVE_SHIPPING_INFO = 'SAVE_SHIPPING_INFO'
